# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncomm.proto\x12\x04\x63omm\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"*\n\x08Response\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x08\x32\x38\n\x04\x43omm\x12\x30\n\x0fGetSerialNumber\x12\r.comm.Request\x1a\x0e.comm.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=20
  _globals['_REQUEST']._serialized_end=43
  _globals['_RESPONSE']._serialized_start=45
  _globals['_RESPONSE']._serialized_end=87
  _globals['_COMM']._serialized_start=89
  _globals['_COMM']._serialized_end=145
# @@protoc_insertion_point(module_scope)
